# Generated by Django 4.2.7 on 2023-11-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(help_text='Придумайте название будущему файлу', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(help_text='Выберите файл на вашем компьютере для получения аудио', upload_to='videos/', verbose_name='Место загрузки файла'),
        ),
    ]
