# Generated by Django 4.2.7 on 2023-11-30 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'видео', 'verbose_name_plural': 'Видео'},
        ),
    ]
