# Generated by Django 4.2.7 on 2023-12-19 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0005_alter_comment_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
